@startuml
class MateriasDTO {
    + CursoNombre : string <<get>> <<set>>
    + NombreMateria : string <<get>> <<set>>
    + CedulaProfesor : int? <<get>> <<set>>
    + Ubicacion : Ubicacione <<get>> <<set>>
    + Horarios : List<Horario> <<get>> <<set>>
}
IDTO <|-- MateriasDTO
@enduml
