@startuml
class UserController {
    - _userManager : IUserServices
    + UserController(user:IUserServices)
    + <<async>> GetUsers() : Task<IActionResult>
    + <<async>> GetUser(cedula:int) : Task<IActionResult>
    + <<async>> Add(user:Usuario) : Task<IActionResult>
    + <<async>> Delete(cedula:int) : Task<IActionResult>
}
ControllerBase <|-- UserController
@enduml
