@startuml
class HorarioCmUbicacione <<partial>> {
    + IdM : int <<get>> <<set>>
    + IdC : int <<get>> <<set>>
    + Codigo : string <<get>> <<set>>
    + IdH : int <<get>> <<set>>
    + <<virtual>> CodigoNavigation : Ubicacione <<get>> <<set>>
    + <<virtual>> IdHNavigation : Horario <<get>> <<set>>
    + <<virtual>> IdMNavigation : Materium <<get>> <<set>>
}
@enduml
