@startuml
class Ubicacione <<partial>> {
    + Codigo : string <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + CodigoP : string <<get>> <<set>>
    + Publico : ulong <<get>> <<set>>
    + Privado : ulong <<get>> <<set>>
    + PlanoImg : int <<get>> <<set>>
    + <<virtual>> Plano : Plano <<get>> <<set>>
    + <<virtual>> Ids : ICollection<Coordenada> <<get>> <<set>>
}
IEntity <|-- Ubicacione
@enduml
