@startuml
class Usuario <<partial>> {
    + Cedula : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Apellido : string <<get>> <<set>>
    + Telefono : int <<get>> <<set>>
    + Direccion : string <<get>> <<set>>
    + Pin : int <<get>> <<set>>
    + Administrador : sbyte? <<get>> <<set>>
    + Operador : sbyte? <<get>> <<set>>
    + TypeUser : string <<get>> <<set>>
}
IEntity <|-- Usuario
@enduml
