@startuml
!include .\\Concrete\Anio.puml
!include .\\Concrete\AnioCurso.puml
!include .\\Concrete\Coordenada.puml
!include .\\Concrete\Curso.puml
!include .\\Concrete\Docente.puml
!include .\\Concrete\EstudiaEn.puml
!include .\\Concrete\Estudiante.puml
!include .\\Concrete\Horario.puml
!include .\\Concrete\HorarioCmUbicacione.puml
!include .\\Concrete\Materium.puml
!include .\\Concrete\Plano.puml
!include .\\Concrete\Ubicacione.puml
!include .\\Concrete\Usuario.puml
!include .\\DTO´s\MateriasCursoDTO.puml
!include .\\DTO´s\UsuarioDTO.puml
@enduml
